Create ecip-randox-revival.md
ethereumclassic/ECIPs pull request #363
Opened 2020-09-05 06:28 UTC by gitr0n1n

+ resubmit proposal to return to WIP or Draft status.

2020-09-11 11:33 UTC, realcodywburns requested changes

2020-09-11 11:33 UTC, realcodywburns commented on _specs/ecip-randox-revival.md
> +ecip: xxxx
please update to ecip 1100

2020-09-11 11:33 UTC, realcodywburns commented on _specs/ecip-randox-revival.md
> +Total donations received: ~3.86 XMR (as of 30th August 2019). Thanks to all contributors.
please add license footer

2020-09-11 17:37 UTC, q9f commented
You already managed to move ECIP 1093 back to draft. This PR does not add any value.

Closing as duplicate of 1093.

2020-09-11 17:37 UTC, closed without merging

2020-09-14 06:24 UTC, gitr0n1n commented
> You already managed to move ECIP 1093 back to draft. This PR does not add any value.
> 
> Closing as duplicate of 1093.

Thanks @q9f .