Admin Clean Up on ecip-1049.md
ethereumclassic/ECIPs pull request #400
Opened 2020-12-03 23:55 UTC by gitr0n1n

+ move to Draft Status (Expired Last Call Review on Oct 9, 2020) due to material redraft of proposal.
+ Update Discussion Thread to new Redraft thread
+ Add Related Discussions Section for archived threads

2020-12-04 09:25 UTC, q9f commented
I think we can continue working on that document, so I would rather send it back to draft status rather than rejecting it.

2020-12-05 16:05 UTC, gitr0n1n commented
> I think we can continue working on that document, so I would rather send it back to draft status rather than rejecting it.

Can that direct movement to `Draft` be made? source: the ECIP diagram.

I see that `Last Call` status can only be moved to `Accepted` or `Rejected`.

`Last Call - An ECIP that is done with its initial iteration and ready for review by a wider audience.`
https://github.com/ethereumclassic/ECIPs/raw/master/assets/ecip-1000/process.png

Pedantic, but thats how the Editors have chosen to follow the ECIP process for all ECIPs.

So move ECIP-1049 to Rejected. Alex resubmits the materially changed `reDraft` proposal to Draft status. Will that require a new ECIP # (like all the Aztlan proposals)?  @q9f

2020-12-07 08:18 UTC, kizoojun01 commented
kizoojun@kizoojunkoi.org

2020-12-07 08:19 UTC, kizoojun01 requested changes
kizoojun@kizoojunki.org

2021-01-19 18:27 UTC, gitr0n1n commented
> I think we can continue working on that document, so I would rather send it back to draft status rather than rejecting it.

@q9f can we get this ECIP moved back to the status it is currently in: `Draft`.

I believe we might needed to have it `Withdrawn` then resubmitted as `Draft`. The issue is that this proposal has past its current review period and now the authors are re-drafting the proposal. It's almost been in this limbo state for 60 days. I think its time to clean this up. I'd do it myself if I was an editor, but those PRs are also sittingon the shelf.

Thanks in advance for the ECIP housekeeping.

2021-02-01 12:14 UTC, q9f commented
I would supporting moving it back to Draft for the time being

2021-02-01 18:10 UTC, bobsummerwill commented
That would make sense to me too, @q9f.

The flow chart in ECIP-1000 does not show a path from Last Call back to Draft, but I don't think we gain anything by forcing the creation of a new, identical ECIP just for the sake of rigid adherence.

2021-02-03 04:11 UTC, TokenHash commented
@gitr0n1n @q9f @bobsummerwill ECIPs can perfectly be moved back to draft. The ECIP process does not specifically say that it can't and the drawing is just a diagram. I drew it like that cause I was copying the Bitcoin one (see below) and for some reason put arrows instead of just lines. I guess I unconsciously put arrows as I was thinking in the forward process, and not about special cases where ECIPs needed to go backward.

![bip-process](https://user-images.githubusercontent.com/29529586/106696238-80309000-6599-11eb-83ff-3a7ad990f4f6.png)

The ECIP process has predecessors in the BIP and EIP processes. EIP says clearly:

```Last Call - This is the final review window for an EIP before moving to FINAL. An EIP editor will assign Last Call status and set a review end date (review-period-end), typically 14 days later.

If this period results in necessary normative changes it will revert the EIP to REVIEW.

Final - This EIP represents the final standard. A Final EIP exists in a state of finality and should only be updated to correct errata and add non-normative clarifications.

Stagnant - Any EIP in DRAFT or REVIEW if inactive for a period of 6 months or greater is moved to STAGNANT. An EIP may be resurrected from this state by Authors or EIP Editors through moving it back to DRAFT.```

BIP say clearly:

```BIPs should be changed from Draft or Proposed status, to Rejected status, upon request by any person, if they have not made progress in three years. Such a BIP may be changed to Draft status if the champion provides revisions that meaningfully address public criticism of the proposal, or to Proposed status if it meets the criteria required as described in the previous paragraph.```

I tried to change the diagram when Wei Tang was harassing the ETC ecosystem arguing the same thing about no backward status changes. The supposed impossibility of moving ECIPs backward to draft was always false, because it is obvious that when an ECIP has a catastrophic problem, no matter what is the status, they have to be moved back to draft to correct issues (as prescribed by the BIP and EIP). 

This has happened in ETH, but I don't remember what case it was.

In conclusion, ECIPs can be moved to draft (I co-wrote ECIP-1000). I will enter the corrected diagram to the assets folder so it is corrected and does not create these confusions again.

Wei was controlling the ECIP-1000 repo at the time of the argument and constantly sabotaging other ECIPs and commentary as he had editor, writing, and author access and authority. That is why I could never change the diagram.

2021-02-03 04:55 UTC, TokenHash commented
@gitr0n1n @q9f @bobsummerwill  

This is the correct diagram for ECIP-1000:

<img width="300" alt="process" src="https://user-images.githubusercontent.com/29529586/106700024-38ae0200-65a1-11eb-80d7-934c0443dbb1.png">

...but I think I messed up when creating the PR from my fork (I haven't used GitHub for a long time  ;)

could one of you add the process.png image to the assets folder pls?

2021-02-04 19:45 UTC, TokenHash commented on _specs/ecip-1049.md
> +status: Rejected
Please change this to `Draft`.

2021-02-05 03:05 UTC, gitr0n1n commented on _specs/ecip-1049.md
> +status: Rejected
Resolved.

2021-02-05 03:12 UTC, gitr0n1n commented
> @gitr0n1n @q9f @bobsummerwill
> 
> This is the correct diagram for ECIP-1000:
> 
> <img alt="process" width="300" src="https://user-images.githubusercontent.com/29529586/106700024-38ae0200-65a1-11eb-80d7-934c0443dbb1.png">
> 
> ...but I think I messed up when creating the PR from my fork (I haven't used GitHub for a long time ;)
> 
> could one of you add the process.png image to the assets folder pls?
> 
> Note that the diagram above is the new correct one, the previous one was not even updated to all the possible statuses that ECIPs may have.

Thanks for clarifying that diagram.

2021-02-05 05:27 UTC, TokenHash commented
@gitr0n1n I just re-learned how to use GitHub....lol....so I entered a PR to update the diagram.

2021-02-05 05:27 UTC, TokenHash approved these changes

2021-02-05 23:35 UTC, bobsummerwill commented
Wei must have polluted my brain with his rigidity about the process, @TokenHash!

2021-02-09 08:01 UTC, q9f approved these changes

2021-02-09 08:01 UTC, q9f commented
Thanks!

2021-02-09 08:01 UTC, merged

2022-04-26 01:26 UTC, Miami87 approved these changes